### ISSUE TITLE
plot_grid is rotating the grid 

### ISSUE THREAD

**Issue by OmegAshEnr01n** [traja-team/traja#100]
The traja plot_grid function seems to be rotating the matrix while plotting. This is quite problematic as the purpose of the function is defeated. 

![image](https://user-images.githubusercontent.com/16122509/194821779-e1142049-ccc0-4349-9272-286af890fd46.png)

![image](https://user-images.githubusercontent.com/16122509/194821808-f677e554-5f2b-40cc-9f87-5a458dd265c9.png)

As you can see this is the plot and the associated histogram plot. This function is especially problematic when the trajectory plot fire is a very narrow rectangle. 

![image](https://user-images.githubusercontent.com/16122509/194822011-2a618cdc-e20e-45d2-8738-c3b956c2822d.png)

**Comment by justinshenk** [comment]
Hi, thanks for pointing this out! The histogram and grid rotation has been
fixed in the latest version (v22.0.0).
