### ISSUE TITLE
User defined(external)/Custom model support

### ISSUE THREAD

**Issue by Saran-nns** [traja-team/traja#30]
Currently, traja.trainer support only traja.models. Add support for user defined models in traja.trainer

**Comment by WolfByttner** [comment]
The trainer currently accepts models exposing a few magic properties. We should make sure these are simplified and documented so users can implement models.

**Comment by WolfByttner** [comment]
@Saran-nns since this is effectively supported now, can we close the issue?

**Comment by Saran-nns** [comment]
Yes, i will close it ;)
