### ISSUE TITLE
Plotly imported but not used

### ISSUE THREAD

**Issue by justinshenk** [traja-team/traja#64]
Plotly is required and imported but not used. Will this be developed further or can we remove it for now?

Line 5 of visualizer.py: `import plotly.express as px`.

The goal is to keep requirements to a minimum.

**Comment by Saran-nns** [comment]
plotly express is used to visualize the latent states at line 37. This class helps to visualize the relation between latent in state space. and thereby one can evaluate latent disentanglement. We have this example in all notebooks that shared recently. But yes, plotly serves this purpose only.

**Comment by justinshenk** [comment]
Thanks for your clarification. It doesn’t appear to be used in the code
(search “px”). Is it still somehow affecting the plots or is it planning to
be developed later?

**Comment by Saran-nns** [comment]
Plotly is used [here](https://github.com/traja-team/traja/blob/3717164b04ec4410f7ed7973ecaa0bc7007ec47a/traja/models/visualizer.py#L37)

**Comment by justinshenk** [comment]
Thanks! I must have missed it.
