### ISSUE TITLE
Periodogram not working

### ISSUE THREAD

**Issue by a-paxton** [traja-team/traja#88]
Hi, there! As part of my review for your JOSS submission, I've been running through your documentation. I'm testing your package from a clean conda env using the conda-forge installation instructions. When I tried to generate the periodogram plot using [the code from your example gallery](https://traja.readthedocs.io/en/latest/gallery/plot_periodogram.html), I ran into an issue:

```
>>> trj = traja.generate()
>>> trj.traja.plot_periodogram('x')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-5ae01ca132cc> in <module>
      1 trj = traja.generate()
----> 2 trj.traja.plot_periodogram('x')

AttributeError: 'TrajaAccessor' object has no attribute 'plot_periodogram'
```

Thanks again for your package!

**Comment by justinshenk** [comment]
Fixed with #91
